### ISSUE TITLE
Project 1 Goals

### ISSUE THREAD

**Issue by sbstiane46** [swilliams2077/Show-Stoppers#4]
1. Who is your target audience?
Heavy content users.  

2. What is the problem that the product will address?
Eliminates the complexity of searching the desired show/movie.  

3. What is the primary goal of the product?  
Streamline users access to entertainment mediums with ease.

4. Identify and prioritize essential user stories?
I should see results related to what I have typed in the search box.
I should be able to see relevant content.

What am I missing?

**Comment by swilliams2077** [comment]
CODE!!!! what is this??? are you serious. You use numbers but don't use bullet points on subtopics. This will not be tolerated.
