### ISSUE TITLE
API

### ISSUE THREAD

**Issue by Vijayalakshmitce** [swilliams2077/Show-Stoppers#5]
1.youtube API should include in the code
2.OMDB api should include in the code

**Comment by Vijayalakshmitce** [comment]
API used in APP:
1youtube and OMDB api using to get the flim response data.
2.Flim name-resppnse.data.name parameter used to get flim name
Flim rating-response.data.rating parameter used to get flim ratinig
Flim Review-response.data.review parameter used to get flim review
flim image-reponse.data.image parameter used to get flim image
flim trailer- response .data.trailer used to get flim trailer

**Comment by smrogers93** [comment]
Good stuff
